(() => {
  'use strict';

  // This public client URL is generated by PushAlert for TifloAcosta.
  // It is intentionally empty until the PushAlert site has been created
  // and its exact Universal Integration URL has been copied here.
  window.TIFLO_PUSHALERT_CONFIG = Object.freeze({
    integrationScriptUrl: ''
  });
})();
